### ISSUE TITLE
Obsoletion results in dangling axioms

### ISSUE THREAD

**Issue by hrshdhgd** [gouttegd/kgcl-java#2] opened 2024-02-15 13:00 UTC
This issue roots from[ this issue in ENVO](https://github.com/EnvironmentOntology/envo/issues/1480). When an obsoletion command is passed to a resource via kgcl, the dangling axioms remain which need to be deleted.

cc: @cmungall

**Comment by gouttegd** [comment] 2024-02-15 13:28
Clarification: obsoletion does not result in _dangling_ axioms. A “dangling” axiom is an axiom that refers to an inexistent entity. After obsoletion, the obsolete entity is still there, it is merely marked as obsolete. Axioms that referred to that entity still point to that very existing entity.

It seems the expected behaviour here was that axioms referring to the to-be-obsoleted entity should be removed. Why not, but if so then that behaviour should be explicitly specified in the KGCL spec (I’ll open an issue there).

For what it’s worth, it’s absolutely not obvious to me that this was the expected behaviour. My position when implementing `NodeObsoletion` was that the operation should just do what it says on the can: obsolete the class. Axioms referring to that class are left in place for an editor to decide what to do with them (removing them is _one_ option, but they could also decide to do something else, such as trying to find an alternative term even if no one had been suggested by the editor who did the obsoletion). Forcefully removing the axioms deprives the editors of the possibility to do that, because they can’t even know that the axioms were there in the first place.

**Closed as completed** 2024-02-15 21:16 UTC
